### ISSUE TITLE
TypeError when changing Configuration Values

### ISSUE THREAD

**Issue by norunoru98** [TheShadowEevee/BDSX-Discord-Chatter-Plugin#1]
TypeError: Assignment to read-only properties is not allowed in strict mode
   at UpdateConfig (C:\server\bdsx-master\plugins\BDSX-Discord-Chatter-Plugin-main\index.ts:279:17)
   at Anonymous function (C:\server\bdsx-master\plugins\BDSX-Discord-Chatter-Plugin-main\index.ts:375:29)
   at CustomCommandImpl.prototype.execute (C:\server\bdsx-master\bdsx\command.ts:185:21)
   at Anonymous function (C:\server\bdsx-master\bdsx\command.ts:220:13)
   at executeCommand (C:\server\bdsx-master\bdsx\command.ts:32:9)

**Comment by TheShadowEevee** [comment]
What have you done before getting this error? Is this a first run?

**Comment by norunoru98** [comment]
I get this problem when I run the (dc config token tokencode) from the console.

**Comment by TheShadowEevee** [comment]
Can you try deleting the plugin and pulling the latest version manually from github?

**Comment by LeontKing2** [comment]
@TheShadowEevee  same happened with me imma try

**Comment by LeontKing2** [comment]
:/
same error still

**Comment by LeontKing2** [comment]
also dc reload says ~~~ Reloading DiscordChatter!
DiscordChatter is disabled. Stopping the reload.

**Comment by TheShadowEevee** [comment]
I'm suprised this hasn't come up in testing, I'll get this figured out as soon as I can.

**Comment by TheShadowEevee** [comment]
Actually the bot disabled message is pretty helpful; that means that either the bot is disabled in the config file (Which I doubt) or that an undefined value is being sent back suggesting that there's an issue with the GetConfig function

**Comment by LeontKing2** [comment]
:/ I do not see any config.json file i only see tsconfig.json thingy

**Comment by TheShadowEevee** [comment]
@LeontKing2 The config file would be in `{bdsx root}/bedrock_server/configs/Discord-Chatter/config.json`

**Comment by TheShadowEevee** [comment]
Fixed in commit be9e654.

Please update now, and let me know if things are working.

NOTE: You will have to delete the old config file. It is in the folder `{BDSX Root}/bedrock_server/configs/Discord-Chatter/config.json`, where "BDSX Root" is the folder with the plugins folder and the bdsx.bat file.

**Comment by norunoru98** [comment]
dc config chanID 848248799335415870
Syntax error: Unexpected "848248799335415870": at "ig chanID >>848248799335415870<<"

[DiscordChatter] Failed to send message to the Discord Server!
[DiscordChatter] Either your Token is incorrect, or the Channel ID is invalid.
[DiscordChatter] Please double check the related values and fix them.

**Comment by TheShadowEevee** [comment]
I see where the new issue is; I'll try to have it fixed sometime within the next 24 hours.

**Comment by TheShadowEevee** [comment]
New bug is fixed in commit b20160a / Version 1.0.2.

Due to precision errors I changed how a channel id is set, now instead of `848248799335415870` like you tried it should be `chanID_848248799335415870` to force a string.

For any new bugs please open a new issue.

**Comment by norunoru98** [comment]
perfect
