### ISSUE TITLE
BDSX Package.json WrongName Error 

### ISSUE THREAD

**Issue by LeontKing2** [TheShadowEevee/BDSX-Discord-Chatter-Plugin#3]
[BDSX-Plugins] Wrong plugin name. Name in 'package.json' must be '@bdsx/BDSX-Discord-Chatter-Plugin-1.0.2' but was '@bdsx/discordchatter'

**Comment by TheShadowEevee** [comment]
This is a side effect of placing the folder into the plugins directory; its safe to ignore.
