### ISSUE TITLE
it tell me to report this?

### ISSUE THREAD

**Issue by bibihool** [TheShadowEevee/BDSX-Discord-Chatter-Plugin#9]
![image](https://user-images.githubusercontent.com/72029878/144541503-b3084364-93f1-4fe6-8a47-636a9608b0d5.png)

**Comment by TheShadowEevee** [comment]
It seems like the internet cut out for a second on the server. As long as the server is operational currently and the bot works as normal that error should be fine to ignore.

**Comment by bibihool** [comment]
ok
